# -*- coding: utf-8 -*-
"""Dashboard Project Big Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18FiHhvy6VgKAjzN6EJsZTdnJqoWqXgSh
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# 1. KONFIGURASI HALAMAN

st.set_page_config(
    page_title="Zara By Group 8",
    page_icon="🛍️",
    layout="wide"
)

# Custom CSS untuk tampilan bersih
st.markdown("""
    <style>
        .block-container {padding-top: 1rem;}
        h1, h2, h3 {font-family: 'Segoe UI', sans-serif;}
        .stMetric {background-color: #F0F2F6; padding: 10px; border-radius: 10px;}
    </style>
""", unsafe_allow_html=True)


# 2. LOAD & BERSIHKAN DATA

@st.cache_data
def load_data():
    try:
        # Load data
        df = pd.read_csv("Zara_sales_db.csv")

        # Pastikan kolom angka benar-benar angka (float/int), bukan text
        cols_to_numeric = ['price', 'Sales Volume']

        for col in cols_to_numeric:
            if col in df.columns:
                # Mengubah ke numerik, jika ada error (huruf) akan jadi NaN
                df[col] = pd.to_numeric(df[col], errors='coerce')


        # Pastikan kolom Cluster jadi string agar warnanya diskrit (bukan gradasi)
        if 'prediction' in df.columns:
            df['Cluster'] = df['prediction'].astype(int).astype(str)
        elif 'Cluster' in df.columns:
             df['Cluster'] = df['Cluster'].astype(str)

        return df
    except FileNotFoundError:
        return None

df_raw = load_data()

if df_raw is not None:

    # 3. SIDEBAR: MULTI-FILTER
    st.sidebar.header("📊 Visualisasi Produk Zara")
    st.sidebar.header("🔍 Filter Data Multi-Layer")

    # Kita copy data asli ke variabel baru untuk difilter bertahap
    df_filtered = df_raw.copy()

    # A. Filter Cluster
    clusters = sorted(df_raw['Cluster'].unique())
    selected_cluster = st.sidebar.multiselect("Pilih Cluster", clusters, default=clusters)
    if selected_cluster:
        df_filtered = df_filtered[df_filtered['Cluster'].isin(selected_cluster)]

    # B. Filter Season
    if 'season' in df_raw.columns:
        seasons = sorted(df_raw['season'].unique())
        selected_season = st.sidebar.multiselect("Pilih Season (Musim)", seasons, default=seasons)
        if selected_season:
            df_filtered = df_filtered[df_filtered['season'].isin(selected_season)]

    # C. Filter Promotion
    if 'Promotion' in df_raw.columns:
        promos = sorted(df_raw['Promotion'].unique())
        # Menggunakan expander agar sidebar tidak terlalu panjang
        with st.sidebar.expander("Filter Promosi & Kategori"):
            selected_promo = st.multiselect("Status Promosi", promos, default=promos)
            if selected_promo:
                df_filtered = df_filtered[df_filtered['Promotion'].isin(selected_promo)]

    # D. Filter Section/Category
    if 'section' in df_raw.columns:
        sections = sorted(df_raw['section'].unique())
        selected_section = st.multiselect("Section (Pria/Wanita)", sections, default=sections)
        if selected_section:
            df_filtered = df_filtered[df_filtered['section'].isin(selected_section)]

    # E. Filter Origin
    if 'Origin' in df_raw.columns:
        origins = sorted(df_raw['Origin'].unique())
        selected_origin = st.multiselect("Origin", origins, default=origins)
        if selected_origin:
            df_filtered = df_filtered[df_filtered['Origin'].isin(selected_origin)]

    # F. Filter Material
    if 'Material' in df_raw.columns:
        materials = sorted(df_raw['Material'].unique())
        selected_material = st.multiselect("Material", materials, default=materials)
        if selected_material:
            df_filtered = df_filtered[df_filtered['Material'].isin(selected_material)]

    # G. Filter Product Position
    if 'Product Position' in df_raw.columns:
        positions = sorted(df_raw['Product Position'].unique())
        selected_position = st.multiselect("Product Position", positions, default=positions)
        if selected_position:
            df_filtered = df_filtered[df_filtered['Product Position'].isin(selected_position)]


    # 4. KPI DASHBOARD

    st.title("🛍️ Zara Sales Performance Dashboard")
    st.caption(f"Menampilkan {df_filtered.shape[0]} produk berdasarkan filter yang dipilih.")

    col1, col2, col3, col4 = st.columns(4)

    avg_sales = df_filtered['Sales Volume'].mean()
    total_sales = df_filtered['Sales Volume'].sum()
    avg_price = df_filtered['price'].mean()
    top_performer = df_filtered.loc[df_filtered['Sales Volume'].idxmax()]['name'] if not df_filtered.empty else "-"

    col1.metric("Rata-rata Penjualan", f"{avg_sales:,.1f} Pcs")
    col2.metric("Total Volume Terjual", f"{total_sales:,.0f}")
    col3.metric("Rata-rata Harga", f"€ {avg_price:.2f}")
    col4.metric("Produk Terlaris", f"{str(top_performer)[:20]}...")

    st.markdown("---")


    # 5. VISUALISASI UTAMA (BARIS 1)

    c_left, c_right = st.columns([2, 1])

    with c_left:
        # VIZ: Rata-rata Penjualan & Harga per Kategori (Group Bar)
        st.subheader("📊 Perbandingan Rata-rata (Sales vs Price)")

        # Pilihan grouping dinamis
        group_col = st.selectbox("Kelompokkan Grafik Berdasarkan:",
                                 ['Cluster', 'season', 'section', 'Promotion'],
                                 index=0)

        # Agregasi Data
        agg_df = df_filtered.groupby(group_col)[['Sales Volume', 'price']].mean().reset_index()

        # Melt agar bisa dibuat grouped bar chart
        agg_melted = agg_df.melt(id_vars=group_col, var_name='Metric', value_name='Value')

        fig_bar = px.bar(
            agg_melted,
            x=group_col,
            y='Value',
            color='Metric',
            barmode='group',
            text_auto='.2s',
            color_discrete_sequence=['#2E86C1', '#E67E22'], # Biru & Oranye
            title=f"Rata-rata Sales & Price per {group_col}",
            height=400
        )
        st.plotly_chart(fig_bar, use_container_width=True)

    with c_right:
        # VIZ: Pie Chart Komposisi
        st.subheader("🍰 Komposisi Data")
        pie_metric = st.radio("Metrik:", ['Sales Volume', 'Jumlah Produk (Count)'], horizontal=True)

        if pie_metric == 'Sales Volume':
            val_col = 'Sales Volume'
            agg_func = None # Pie chart default sum values
        else:
            val_col = group_col # Dummy col
            # Untuk count, kita perlu trik sedikit
            agg_func = None

        if pie_metric == 'Sales Volume':
            fig_pie = px.pie(
                df_filtered,
                names=group_col,
                values='Sales Volume',
                hole=0.4,
                title=f"Share Sales Volume per {group_col}",
                color_discrete_sequence=px.colors.qualitative.Pastel
            )
        else:
            # Hitung count manual agar akurat
            count_df = df_filtered[group_col].value_counts().reset_index()
            count_df.columns = [group_col, 'Count']
            fig_pie = px.pie(
                count_df,
                names=group_col,
                values='Count',
                hole=0.4,
                title=f"Proporsi Jumlah Produk per {group_col}",
                color_discrete_sequence=px.colors.qualitative.Pastel
            )

        st.plotly_chart(fig_pie, use_container_width=True)


    # 6. FITUR TOP N PRODUCTS (BARIS 2)

    st.markdown("---")
    st.subheader("🏆 Top Produk (Berdasarkan Filter)")

    col_top_control, col_top_viz = st.columns([1, 3])

    with col_top_control:
        n_products = st.slider("Jumlah Produk Ditampilkan:", 5, 20, 10)
        sort_asc = st.checkbox("Tampilkan Produk Terendah (Bottom)", value=False)

    with col_top_viz:
        # Sort data berdasarkan Sales
        top_df = df_filtered.sort_values(by='Sales Volume', ascending=sort_asc).head(n_products)

        fig_top = px.bar(
            top_df,
            x='Sales Volume',
            y='name', # Ganti 'name' dengan nama kolom produk Anda jika beda
            orientation='h',
            color='Cluster',
            text='Sales Volume',
            title=f"Top {n_products} Produk {'Terendah' if sort_asc else 'Tertinggi'} (Sales)",
            color_discrete_sequence=px.colors.qualitative.Bold,
            height=400 + (n_products * 10) # Tinggi dinamis
        )
        fig_top.update_layout(yaxis={'categoryorder':'total ascending'}) # Urutkan visual
        st.plotly_chart(fig_top, use_container_width=True)


    # 7. DETAIL SEBARAN (SCATTER)

    with st.expander("📍 Lihat Detail Sebaran (Scatter Plot)"):
        st.markdown("Grafik ini menunjukkan posisi setiap produk. Arahkan mouse untuk melihat detail nama.")

        fig_scatter = px.scatter(
            df_filtered,
            x='price',
            y='Sales Volume',
            color=group_col,
            hover_data=['name', 'Cluster', 'season'],
            title=f"Hubungan Price vs Sales (Dikelompokkan oleh {group_col})",
            opacity=0.7,
            height=500
        )
        st.plotly_chart(fig_scatter, use_container_width=True)

else:
    st.error("Data tidak ditemukan. Pastikan file 'Zara_sales_final_complete.csv' ada di folder yang sama.")